### PR TITLE
[Enhancement][REDO] ternModuleInstalls to support folders within a plug-in JAR per Issue #332

### PR DESCRIPTION
**Pull request by demonfiddler**
At Angelo's request following his recent extensive refactoring, this is a re-submission of my Pull Request for the implementation for Issue #332.

P.S. @angelozerr I'm a total Git newbie and am not particularly confident that I have correctly used the Git CLI to fetch & merge your recent commits. Please let me know if you hit any problems.

Thanks,

--A

### CODE REVIEW

**Comment by angelozerr** [comment]
Thanks @demonfiddler!

**Comment by demonfiddler** [comment]
Thanks for the merge @angelozerr. Did you have any further thoughts about removing/deprecating support for the ZIP-format repository contribution now that we can just bundle the stuff in a plug-in folder? I didn't prepare a specific test case for the latter in case you intended to remove the ZIP support, in which case we could simply modify the existing test case to suit the new packaging.

**Comment by angelozerr** [comment]
>  Did you have any further thoughts about removing/deprecating support for the ZIP-format repository contribution now that we can just bundle the stuff in a plug-in folder? 

Please do a PR for that. I think you are the first guy who is using this feature. Please update if possible the samples.

**Comment by demonfiddler** [comment]
Will do.

**Pull request merged**
