### PR TITLE
Include sources into p2-repository

### PR DESCRIPTION
**Pull request by dgolovin**

### CODE REVIEW

**Comment by dgolovin** [comment]
@paulvi I added some info to article. There is no way to send PR for wiki, so I mirrored it and here is the link which compares latest revision in original wiki with my commit.

https://github.com/dgolovin/tern.java-wiki/compare/2a3572d...master

**Comment by angelozerr** [comment]
> There is no way to send PR for wiki

You cannot modify wiki pag eas you wish? @paulvi is able to change wiki pages.

**Comment by angelozerr** [comment]
This PR breaks now the build https://travis-ci.org/angelozerr/tern.java/builds/48020724

@dgolovin could you see the problem please. Do you think it's possible to see the problem quickly, because I would like to commit other features like ecma6. 

Thanks for your help.

**Comment by angelozerr** [comment]
@dgolovin I'm waiting for your answer today. If I have not answer from you I will revert your PR.

I will commit soon several features (like ecma6 support) and I would like to provide it quickly. Hoep you will understand.

Thanks for your help!

**Comment by dgolovin** [comment]
@angelozerr this build failure seems to be related to broken zip in local repository.
```
[ERROR] Internal error: org.eclipse.tycho.core.osgitools.OsgiManifestParserException: Exception parsing OSGi MANIFEST /home/travis/.m2/repository/p2/osgi/bundle/org.mozilla.javascript/1.7.4.v201209142200/org.mozilla.javascript-1.7.4.v201209142200.jar: error in opening zip file
```

**Comment by angelozerr** [comment]
> It also marked with green check in PR closed PR list as 'Success: The Travis CI build passed'.

Yes it's stange, but if you go at https://github.com/angelozerr/tern.java yopu will see that build icon travis is error. Have you an idea how to fix that?

**Comment by dgolovin** [comment]
Last build is good :)

**Comment by angelozerr** [comment]
> Last build is good :)

Cool! Sorry for the noise.

**Comment by angelozerr** [comment]
@dgolovin `minimal-json` appears now inside `uncategorized` category. I think it should be better that it appears inside `Tern IDE` category. What do you think? Could you change that please?

**Comment by angelozerr** [comment]
@dgolovin we have released tern.java + AngularJS Eclipse, but I have a problem when I try to update marketplace https://marketplace.eclipse.org/content/tern-eclipse-ide with minimal-json.

Now minimal-json is not a feature bu a bundle. I can add features in marketplace but not bundle. So marketplace doesn't work -(

Do you know how I could fix that please? Thanks!

**Comment by gamerson** [comment]
Can you not just add the minimal-json bundle into one of your feature.xml
files?  Just add it as another <plugin.../>

On Wed, Jan 28, 2015 at 4:37 PM, Angelo <notifications@github.com> wrote:

> @dgolovin <https://github.com/dgolovin> we have released tern.java +
> AngularJS Eclipse, but I have a problem when I try to update marketplace
> https://marketplace.eclipse.org/content/tern-eclipse-ide with
> minimal-json.
>
> Now minimal-json is not a feature bu a bundle. I can add features in
> marketplace but not bundle. So marketplace doesn't work -(
>
> Do you know how I could fix that please? Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/angelozerr/tern.java/pull/215#issuecomment-71798437>.
>



-- 
Greg Amerson
Liferay Developer Tools
Liferay, Inc. www.liferay.com

**Comment by paulvi** [comment]
Yes, minimal-json should be just a dependency of some feature and Eclipse will resolve to get it.

Having it as separate item that use has to select is error prone.

**Comment by angelozerr** [comment]
Ok problem is now fixed. Problem cames from that bundle of minimal-json was not included in the update site. @pascalleclercq has fixed the problem and release for 0.8.0 works great now.

Thanks @pascalleclercq !

**Pull request merged**
